{{-- resources/views/content/invoices/index.blade.php --}}
@extends('layouts/layoutMaster')

@section('title', $title ?? 'Invoices')

{{-- Styles --}}
@section('vendor-style')
  <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/css/dataTables.bootstrap5.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-responsive-bs5/css/responsive.dataTables.css') }}">
@endsection

{{-- Scripts: jQuery + DataTables (must be before $dataTable->scripts) --}}
@section('vendor-script')
  <script src="{{ asset('assets/vendor/libs/jquery/jquery.js') }}"></script>
  <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/dataTables.js') }}"></script>
  <script src="{{ asset('assets/vendor/libs/datatables-bs5/js/dataTables.bootstrap5.js') }}"></script>
  <script src="{{ asset('assets/vendor/libs/datatables-responsive-bs5/js/dataTables.responsive.js') }}"></script>
@endsection

@section('content')
 
  <div class="card mb-3">
    <div class="card-header d-flex align-items-center justify-content-between">
      <h4 class="mb-0">Invoices</h4>
    </div>
    <div class="card-body">

      {{-- Filters --}}
      <div class="row g-2 mb-3">
        <div class="col-md-3">
          <label class="form-label mb-1">Billing Month</label>
          <input
            type="month"
            id="filter_month"
            class="form-control"
            value="{{ request('month', now()->format('Y-m')) }}"
          >
        </div>

        <div class="col-md-4">
          <label class="form-label mb-1">Project (optional)</label>
          <select id="filter_project" class="form-select">
            <option value="">All</option>
            @foreach($projects as $p)
              <option value="{{ $p->id }}" {{ (string)$p->id === (string)request('project_id') ? 'selected' : '' }}>
                {{ $p->project_name }}
              </option>
            @endforeach
          </select>
        </div>

        <div class="col-md-4">
          <label class="form-label mb-1">Customer (optional)</label>
          <select id="filter_customer" class="form-select">
            <option value="">All</option>
            @foreach($customers as $c)
              <option value="{{ $c->id }}" {{ (string)$c->id === (string)request('customer_id') ? 'selected' : '' }}>
                {{ $c->name }}
              </option>
            @endforeach
          </select>
        </div>

        <div class="col-md-1 d-flex align-items-end">
          <div class="d-grid w-100">
            <button type="button" id="btnFilter" class="btn btn-primary">Go</button>
          </div>
        </div>
      </div>

      {{-- Table generated by the DataTable service class --}}
      {!! $dataTable->table(['class' => 'table table-striped table-bordered w-100', 'style' => 'width:100%']) !!}

      {{-- Debug box (shown when server returns non-JSON) --}}
      <div id="dt-error" class="alert alert-danger mt-3 d-none" role="alert">
        <div class="fw-bold mb-1">Failed to load invoices.</div>
        <div class="small">Open the browser console for details. If you see HTML (login page / Whoops), fix that server error.</div>
      </div>

    </div>
  </div>
 
@endsection

@section('extra-script')
  {{-- DataTables init script emitted by the service class --}}
  {!! $dataTable->scripts() !!}

  <script>
    // Ensure POST requests from DataTables include CSRF (prevents 419 => "Invalid JSON")
    $.ajaxSetup({
      headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' }
    });

    (function () {
      const TABLE_ID = 'invoice-table';

    // Helper: "YYYY-MM" -> "MM-YYYY"
    function toMY(v) {
      const m = /^(\d{4})-(\d{2})$/.exec((v || '').trim());
      return m ? `${m[2]}-${m[1]}` : v;
    }

    // Attach filters to every Ajax request
    $(document).on('preXhr.dt', '#' + TABLE_ID, function (e, settings, data) {
      const rawMonth = document.getElementById('filter_month')?.value || '';
      data.month       = toMY(rawMonth); // <-- converted to m-Y here
      data.project_id  = document.getElementById('filter_project')?.value || '';
      data.customer_id = document.getElementById('filter_customer')?.value || '';
    });
      // 2) Hook error handler to show a friendly message and dump server reply in console
      $(document).on('error.dt', '#' + TABLE_ID, function (e, settings, techNote, message) {
        console.error('DataTables error:', message);
        try {
          const xhr = settings.jqXHR;
          if (xhr && xhr.responseText) {
            console.log('AJAX response preview:', xhr.responseText.substring(0, 1500));
          }
        } catch (err) {}
        document.getElementById('dt-error')?.classList.remove('d-none');
      });

      // 3) Filter actions → reload
      function reloadDT() {
        const dt = window.LaravelDataTables && window.LaravelDataTables[TABLE_ID];
        if (dt) dt.ajax.reload();
      }
      document.getElementById('btnFilter')?.addEventListener('click', reloadDT);
      ['filter_month','filter_project','filter_customer'].forEach(id => {
        document.getElementById(id)?.addEventListener('change', reloadDT);
      });

      // 4) If you land on this page with query params, force initial reload so they apply
      // (The first draw might have happened before preXhr was attached in some setups.)
      window.addEventListener('load', function () {
        setTimeout(reloadDT, 100);
      });
    })();
  </script>
@endsection
